import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammmad Kashif
 */
public class medicinedetails1 extends javax.swing.JFrame {

    /**
     * Creates new form medicinedetails1
     */
    public medicinedetails1() {
        initComponents();
        panel2.setBackground(new Color(255,255,255,100));
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        sideeffects2 = new javax.swing.JTextField();
        dose2 = new javax.swing.JTextField();
        ref2 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        issue2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        expiry2 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        compony2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        advice2 = new javax.swing.JTextField();
        dd2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        depttable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 102, 204));
        jLabel35.setText("Name Of Tablet");
        panel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 37, -1, 35));

        sideeffects2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideeffects2sideeffectsActionPerformed(evt);
            }
        });
        panel2.add(sideeffects2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 229, 32));

        dose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dose2doseActionPerformed(evt);
            }
        });
        panel2.add(dose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 244, 229, 32));

        ref2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ref2refActionPerformed(evt);
            }
        });
        panel2.add(ref2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 185, 229, 35));

        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2nameActionPerformed(evt);
            }
        });
        panel2.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 40, 229, 32));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 204));
        jLabel36.setText("Ref#");
        panel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 183, -1, 35));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 102, 204));
        jLabel37.setText("Daily Dose");
        panel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 105, 35));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 204));
        jLabel38.setText("Dose(mg)");
        panel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 241, 105, 35));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 204));
        jLabel39.setText("Possible SideEffects");
        panel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, 35));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 204));
        jLabel40.setText("Issue Date");
        panel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 332, 105, 35));

        issue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue2issueActionPerformed(evt);
            }
        });
        panel2.add(issue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 335, 229, 32));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 204));
        jLabel41.setText("Expiry Date");
        panel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 373, 105, 35));

        expiry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiry2expiryActionPerformed(evt);
            }
        });
        panel2.add(expiry2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 376, 229, 32));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 204));
        jLabel42.setText("Storage Advice");
        panel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 461, -1, 35));

        compony2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compony2componyActionPerformed(evt);
            }
        });
        panel2.add(compony2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 417, 229, 32));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 204));
        jLabel43.setText("Compony name");
        panel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 414, -1, 35));

        advice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advice2adviceActionPerformed(evt);
            }
        });
        panel2.add(advice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 464, 229, 32));

        dd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dd2ddActionPerformed(evt);
            }
        });
        panel2.add(dd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 123, 229, 32));

        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 204));
        jButton3.setText("ADD MEDICINE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3jButton1ActionPerformed(evt);
            }
        });
        panel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 211, 201, 44));

        jButton8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 204));
        jButton8.setText("REMOVE MEDICINE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8jButton4ActionPerformed(evt);
            }
        });
        panel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 211, -1, 44));

        jButton9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 204));
        jButton9.setText("UPDATE MEDICINE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9jButton5ActionPerformed(evt);
            }
        });
        panel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 211, 201, 44));

        depttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        depttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depttableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(depttable);

        panel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 273, 683, 218));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("MEDICINE DETAILS");
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 78, 429, 105));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/home.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 63, 39));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 204));
        jLabel44.setText("Price ");
        panel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 502, -1, 35));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricecomponyActionPerformed(evt);
            }
        });
        panel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 505, 229, 32));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 102, 204));
        jLabel45.setText("Qunatity Avaliable");
        panel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 549, -1, 35));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityadviceActionPerformed(evt);
            }
        });
        panel2.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 549, 229, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/capsule.png"))); // NOI18N
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 103, -1, -1));

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 720));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/medbackground_1.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1330, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sideeffects2sideeffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideeffects2sideeffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideeffects2sideeffectsActionPerformed

    private void dose2doseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dose2doseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dose2doseActionPerformed

    private void ref2refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ref2refActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ref2refActionPerformed

    private void name2nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2nameActionPerformed

    private void issue2issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue2issueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issue2issueActionPerformed

    private void expiry2expiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiry2expiryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiry2expiryActionPerformed

    private void compony2componyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compony2componyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compony2componyActionPerformed

    private void advice2adviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advice2adviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advice2adviceActionPerformed

    private void dd2ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dd2ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dd2ddActionPerformed

    private void jButton3jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false","root","asif");
            PreparedStatement pst = conn.prepareStatement("insert into medicine"+"(name,dailydose,refno,dose,sideeffects,issuedate,expirydate,componyname,storage,price,quantity)"+" values(?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,name2.getText());
            pst.setString(2,dd2.getText());
            pst.setString(3,ref2.getText());
            pst.setString(4,dose2.getText());
            pst.setString(5,sideeffects2.getText());
            pst.setString(6,issue2.getText());
            pst.setString(7,expiry2.getText());
            pst.setString(8,compony2.getText());
            pst.setString(9,advice2.getText());
 pst.setString(10,price.getText());
            pst.setString(11,quantity.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Medicine Added Sucessfully");
            showTableData();
            name2.setText(null);
            dd2.setText(null);
            ref2.setText(null);
            dose2.setText(null);
            sideeffects2.setText(null);
            issue2.setText(null);
            expiry2.setText(null);
            compony2.setText(null);
            advice2.setText(null);
            price.setText(null);
             quantity.setText(null);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_jButton3jButton1ActionPerformed

    private void jButton8jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8jButton4ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false","root","asif");
            PreparedStatement pst = conn.prepareStatement("delete from medicine where refno=?");
            pst.setString(1,ref2.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Deleted Sucessfully");
            showTableData();
            name2.setText(null);
            dd2.setText(null);
            ref2.setText(null);
            dose2.setText(null);
            sideeffects2.setText(null);
            issue2.setText(null);
            expiry2.setText(null);
            compony2.setText(null);
            advice2.setText(null);
            price.setText(null);
            quantity.setText(null);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton8jButton4ActionPerformed
public void showTableData(){
    try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false","root","asif");
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM hospitalmanagementsystem.medicine");
 ResultSet rs=pst.executeQuery();         
 depttable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}
    private void jButton9jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9jButton5ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false","root","asif");
            PreparedStatement pst = conn.prepareStatement("UPDATE medicine SET name=?,dailydose=?,dose=?,sideeffects=?,issuedate=?,expirydate=?,componyname=?,storage=?,price=?,quantity=? WHERE refno=?");

            pst.setString(1,name2.getText());
            pst.setString(2,dd2.getText());

            pst.setString(3,dose2.getText());
            pst.setString(4,sideeffects2.getText());
            pst.setString(5,issue2.getText());
            pst.setString(6,expiry2.getText());
            pst.setString(7,compony2.getText());
            pst.setString(8,advice2.getText());
             pst.setString(9,price.getText());
            pst.setString(10,quantity.getText());
            pst.setString(11,ref2.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Updated Sucessfully");
            showTableData();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton9jButton5ActionPerformed

    private void depttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depttableMouseClicked
        int SelectedRow =depttable.getSelectedRow();
        DefaultTableModel table=(DefaultTableModel)depttable.getModel();
        name2.setText(table.getValueAt(SelectedRow, 0).toString());
        dd2.setText(table.getValueAt(SelectedRow, 1).toString());
        ref2.setText(table.getValueAt(SelectedRow, 2).toString());
        dose2.setText(table.getValueAt(SelectedRow, 3).toString());
        sideeffects2.setText(table.getValueAt(SelectedRow, 4).toString());
        issue2.setText(table.getValueAt(SelectedRow, 5).toString());
        expiry2.setText(table.getValueAt(SelectedRow, 6).toString());
        compony2.setText(table.getValueAt(SelectedRow, 7).toString());
        advice2.setText(table.getValueAt(SelectedRow, 8).toString());
        price.setText(table.getValueAt(SelectedRow, 9).toString());
        quantity.setText(table.getValueAt(SelectedRow, 10).toString());
    }//GEN-LAST:event_depttableMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Index ap=new  Index();
        ap.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void pricecomponyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricecomponyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricecomponyActionPerformed

    private void quantityadviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityadviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityadviceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicinedetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicinedetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicinedetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicinedetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicinedetails1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advice2;
    private javax.swing.JTextField compony2;
    private javax.swing.JTextField dd2;
    private javax.swing.JTable depttable;
    private javax.swing.JTextField dose2;
    private javax.swing.JTextField expiry2;
    private javax.swing.JTextField issue2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name2;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField ref2;
    private javax.swing.JTextField sideeffects2;
    // End of variables declaration//GEN-END:variables
}
